#ifndef DEFINES_H_
#define DEFINES_H_
//SIZES
#define SIZE_ARRAY_CLIENTS 50
#define SIZE_ARRAY_LOANS 50
#define SIZE_CHAR_ARRAY 50

#define RETRIES 4
//RESULTS
#define OK 0
#define ERROR -1
//STATES
#define EMPTY 1
#define NO_EMPTY 0
//MAIN MENU
#define ADD_CLIENT 1
#define MODIFY_CLIENT 2
#define DELETE_CLIENT 3
#define NEW_LOAN 4
#define PAY_LOAN 5
#define RESUME_LOAN 6
#define SHOW_CLIENTS 7
#define SHOW_LOANS 8
#define REPORTS_CLIENTS 9
#define REPORTS_LOANS 10
#define EXIT 11
//MODIFY CLIENTS MENU
#define MODIFY_NAME 1
#define MODIFY_LASTNAME 2
#define MODIFY_CUIL 3
//REPORTS CLIENTS MENU
#define CLIENT_MORE_ACTIVE_LOANS 1
#define CLIENT_MORE_ACTIVE_PAYED 2
#define CLIENT_MORE_LOANS 3
//REPORTS LOANS MENU
#define LOANS_UPPER 1
#define LOANS_BY_IMPORT 2
#define LOANS_PAID_OUT 3
#define LOANS_BY_QUANTITY_FEE 4

#define STATE_ACTIVE "ACTIVO"
#define STATE_PAYED "SALDADO"

#endif /* DEFINES_H_ */
